```http

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "studentId": "admin",
  "password": "admin123"
}

### Get all students
GET {{baseUrl}}/students
Accept: application/json
Authorization: Bearer {{token}}

### Get student by ID
GET {{baseUrl}}//students/s3
Accept: application/json
Authorization: Bearer {{token}}

### Create a student
POST {{baseUrl}}/students
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "studentId": "s3",
  "name": "Ali",
  "email": "ali@campus.com",
  "password": "password123",
  "role": "STUDENT"
}

### Get all rooms
GET {{baseUrl}}/rooms
Accept: application/json
Authorization: Bearer {{token}}

### Create a room
POST {{baseUrl}}/rooms
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roomNumber": "R101",
  "type": "MEETING_ROOM",
  "capacity": 30
}

### Get all bookings
GET {{baseUrl}}/bookings
Accept: application/json
Authorization: Bearer {{token}}

### Create a booking
POST {{baseUrl}}/bookings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "studentId": 5,
  "roomId": 1
}
